#!/bin/bash

. .git/hooks/fightclub_git_plugin/common.sh


if ! does_pivotal_card_number_begin_commit_message_file "${1}"; then
	echo "Associated Pivotal Card Number has not been given.  What the Facebook?" 
	exit 1
fi

echo -n "checking for card number ${pivotal_card_number} in pivotal..."

if confirm_pivotal_card_number_exists $(get_pivotal_card_number_from_commit_message_file); then
	echo "ok"
else
	exit 1;
fi
